name = "EarCut"
uuid = "5160dea5-cc57-53b0-be5f-ac191989508a"
version = "2.0.0"

[deps]
EarCut_jll = "5ae413db-bbd1-5e63-b57d-d24a61df00f5"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
